[request_definition]
r = sub, dom, obj, act

[policy_definition]
p = sub, dom, obj, act, eft

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow)) && !some(where (p.eft == deny))

[matchers]
m = (g(r.sub, p.sub) || r.sub == p.sub) && (r.dom == p.dom || p.dom == "acl:public" || p.dom == "acl:share") && (r.obj == p.obj || key_match(r.obj, p.obj)) && (r.act == p.act || p.act=="*")