#!/usr/bin/env bash
python -m pip install -e . --ignore-installed --no-dependencies
jupyter serverextension enable --sys-prefix jupyter_server_proxy
jupyter labextension install @jupyterlab/plotly-extension
